# Основы Python


### Задание 1

Даны 2 переменных, в которых хранятся строки произвольной длины: phrase_1 и phrase_2.
Напишите код, который проверяет какая из этих строк длиннее.

Примеры работы программы:

phrase_1 = 'Насколько проще было бы писать программы, если бы не заказчики’
phrase_2 = '640Кб должно хватить для любых задач. Билл Гейтс (по легенде)'
Результат:
Фраза 1 длиннее фразы 2

phrase_1 = '640Кб должно хватить для любых задач. Билл Гейтс (по легенде)'
phrase_2 = 'Насколько проще было бы писать программы, если бы не заказчики’
Результат:
Фраза 2 длиннее фразы 1

phrase_1 = 'Насколько проще было бы писать программы, если бы не заказчики’
phrase_2 = 'Насколько проще было бы писать программы, если бы не заказчики’
Результат:
Фразы равной длины

### Решение

In [1]:
phrase_1 = 'Я не хочу стать какой-нибудь там звездой, я стану легендой! Фредди Меркьюри (цитата)'
phrase_2 = 'Стремитесь не к успеху, а к ценностям, которые он дает. Альберт Эйнштейн (цитата)'
if len(phrase_1) > len(phrase_2):
    print(phrase_1, 'длиннее чем phrase_2')
elif len(phrase_2) < len(phrase_2):
    print(phrase_2, 'длинее чем phrase_1')
else:
    print('Обе фразы одинаковой длины')
print('Конец программы')

Я не хочу стать какой-нибудь там звездой, я стану легендой! Фредди Меркьюри (цитата) длиннее чем phrase_2
Конец программы


### Задание 2

Дана переменная, в которой хранится четырехзначное число (год). Необходимо написать программу, которая выведет, является ли данный год високосным или обычным.

Пример работы программы:

year = 2020
Результат:
Високосный год

year = 2019
Результат:
Обычный год

### Решение

In [2]:
"""Чтобы определить, является ли год високосным, выполните следующие действия:

1. Если год делится на 4 без остатка, перейдите на шаг 2. В противном случае перейдите к выполнению действия 5.
2. Если год делится на 100 без остатка, перейдите на шаг 3. В противном случае перейдите к выполнению действия 4.
3. Если год делится на 400 без остатка, перейдите на шаг 4. В противном случае перейдите к выполнению действия 5.
4. Год високосный (366 дней).
5. Год не високосный год (365 дней)."""

x=int(input('Введите год'))
# проверим шаг 1
if x%4 != 0:
    print('Год не високосный')
# проверим шаг 2
elif x%100 == 0:
    # проверим шаг 3
    if x%400 == 0:
        print('Год високосный')
    else:
        print('Год не високосный')
else:
    print('Год високосный')
print('Конец программы')

Введите год2020
Год високосный
Конец программы


### Задание 3

Необходимо написать программу, которая будет запрашивать у пользователя месяц и дату рождения и выводить соответствующий знак зодиака.

Пример работы программы:

Введите день:
30

Введите месяц:
Август
Результат:
Ваш знак зодиака: Дева

Введите день:
29

Введите месяц:
Октябрь
Результат:
Ваш знак зодиака: Скорпион

### Решение

In [3]:
y=int(input('Введите свой месяц рождения в формате числа от 1 до 12'))
x=int(input('Введите свой день рождения в формате числа от 1 до 31'))
if (y == 3 and 21 <= x <= 31) or (y == 4 and 1 <= x <= 19): 
    print('Ваш знак зодиака: Овен')
elif (y == 4 and 20 <= x <= 30) or (y == 5 and 1 <= x <= 20): 
    print('Ваш знак зодиака: Телец')
elif (y == 5 and 21 <= x <= 31) or (y == 6 and 1 <= x <= 20): 
    print('Ваш знак зодиака: Близнецы')
elif (y == 6 and 21 <= x <= 30) or (y == 7 and 1 <= x <= 22): 
    print('Ваш знак зодиака: Рак')
elif (y == 7 and 23 <= x <= 31) or (y == 8 and 1 <= x <= 22): 
    print('Ваш знак зодиака: Лев')
elif (y == 8 and 23 <= x <= 31) or (y == 9 and 1 <= x <= 22): 
    print('Ваш знак зодиака: Дева')
elif (y == 9 and 23 <= x <= 30) or (y == 10 and 1 <= x <= 22): 
    print('Ваш знак зодиака: Весы')
elif (y == 10 and 23 <= x <= 31) or (y == 11 and 1 <= x <= 21): 
    print('Ваш знак зодиака: Скорпион')
elif (y == 11 and 22 <= x <= 30) or (y == 12 and 1 <= x <= 21): 
    print('Ваш знак зодиака: Стрелец')
elif (y == 1 and 22 <= x <=31) or (y == 12 and 1 <= x <= 1): 
    print('Ваш знак зодиака: Козерог')
elif (y == 1 and 20 <= x <= 31) or (y == 2 and 1<= x <= 18): 
    print('Ваш знак зодиака: Водолей')
elif (y == 2 and 19 <= x <= 29) or (y == 3 and 1 <= x <= 20): 
    print('Ваш знак зодиака: Рыбы')
else:
    print('Неверная дата рождения')

Введите свой месяц рождения в формате числа от 1 до 1211
Введите свой день рождения в формате числа от 1 до 314
Ваш знак зодиака: Скорпион


### Задание 4

Вам нужно написать программу для подбора упаковок по размерам товара. Размеры хранятся в переменных (в сантиметрах):

width = 10
length = 205
height = 5
Используйте следующие правила:

если каждое из трех измерений менее 15 сантиметров, то выведите на экран “Коробка №1”;
если хотя бы одно из измерений больше 15 сантиметров, но менее 50 сантиметров, то выводите “Коробка №2”;
если длина товара больше 2 метров, то выводите “Упаковка для лыж”;
во всех остальных случаях выводите “Стандартная коробка №3”.

### Решение

In [4]:
width = 10
length = 205
heigth = 5

if width < 15 and length < 15 and height < 15:
    print('Коробка №1')
elif length > 200:
    print('Упаковка для лыж')
elif 15 < width < 50 or 15 < length < 50 or 15 < height < 50:
    print('Коробка №2')
else:
    print('Стандартная коробка №3')

Упаковка для лыж


### Задание 5

Дана переменная, в которой хранится шестизначное число (номер проездного билета). Напишите программу, которая будет определять, является ли данный билет “счастливым”. Билет считается счастливым, если сумма первых трех цифр совпадает с суммой последних трех цифр номера.

Примеры работы программы:

number = 123456
Результат:
Неасчастливый билет

number = 123321
Результат:
Счастливый билет

### Решение

In [7]:
a = int(input('Введите шестизначный номер проездного билета'))
b = a // 100000
c = (a // 10000) - 10
d = (a // 1000) - (100 + c * 10)
e = (a // 100) - (1000 + c * 100 + d * 10)
f = (a // 10) - (10000 + c * 1000 + d * 100 + e * 10)
g = a%10
h = b + c + d
i = e + f + g
if h == i:
    print('Поздравляем! У Вас счастливый билет')
else:
    print('Сожалеем, Ваш билет несчастливый')

Введите шестизначный номер проездного билета123321
Поздравляем! У Вас счастливый билет


### Задание 6

Напишите программу, которая сможет вычислять площади трех фигур (круг, треугольник и прямоугольник). Тип фигуры запрашиваем через пользовательский ввод, после чего делаем запрос характеристик фигуры:

если пользователь выбрал круг, запрашиваем его радиус,
если треугольник – длины трех его сторон;
если прямоугольник – длины двух его сторон.
Пример работы программы:

Введите тип фигуры:
Круг

Введите радиус круга:
10
Результат:
Площадь круга: 314.16

Введите тип фигуры:
Треугольник

Введите длину стороны A:
2

Введите длину стороны B:
2

Введите длину стороны C:
3
Результат:
Площадь треугольника: 1.98

### Решение

In [5]:
a = input('Введите название фигуры используя маленький регистр')
if a =='круг':
    d = int(input('Введите радиус'))
    print('Площадь круга равна:', round(d ** 2 * 3.1415, 2))
elif a == 'треугольник':
    b = int(input('Введите длину стороны А'))
    c = int(input('Введите длину стороны B'))
    d = int(input('Введите длину стороны C'))
    p = (b + c + d) / 2
    pritn('Площадь треугольника равна', round(sqrt(p*(p-b)*(p-c)*(p-d)), 2))
elif a =='прямоугольник':
    e = int(input('Введите длину стороны A'))
    f = int(input('Введите длину стороны B'))
    print('Площадь прямоугольника равна', round(e * f))
else:
    print('Фигура не соответсвует условию')

Введите название фигуры используя маленький регистркруг
Введите радиус5
Площадь круга равна: 78.54


# Управляющие конструкции и коллекции

### Задание 1

Дана переменная, в которой хранится слово из латинских букв. Напишите код, который выводит на экран:

среднюю букву, если число букв в слове нечетное;
две средних буквы, если число букв четное.
Примеры работы программы:

word = ‘test’
Результат:
es

word = ‘testing’
Результат:
t

### Решение

In [8]:
word = 'test'

if len(word)%2 == 0:
    print(word[int(len(word) / 2) - 1 : int(len(word) / 2 + 1)])
elif len(word)%2 != 0:
    print(word[int(len(word) // 2)])

es


### Задание 2
Напишите программу, которая последовательно запрашивает у пользователя числа (по одному за раз) и после первого нуля выводит сумму всех ранее введенных чисел.

Примеры работы программы:

Введите число:
1

Введите число:
4

Введите число:
6

Введите число:
0
Результат:
11

Введите число:
0
Результат:
0

### Решение

In [9]:
user_input = int(input('Введите число'))
sum_ = 0
while user_input != 0:
    sum_ += user_input
    user_input = int(input('Введите число'))
print(sum_)
print('Конец программы')

Введите число1
Введите число2
Введите число3
Введите число4
Введите число5
Введите число0
15
Конец программы


### Задание 3
Мы делаем MVP dating-сервиса, и у нас есть список парней и девушек.
Выдвигаем гипотезу: лучшие рекомендации мы получим, если просто отсортируем имена по алфавиту и познакомим людей с одинаковыми индексами после сортировки! Но мы не будем никого знакомить, если кто-то может остаться без пары:

Примеры работы программы:

boys = [‘Peter’, ‘Alex’, ‘John’, ‘Arthur’, ‘Richard’]
girls = [‘Kate’, ‘Liza’, ‘Kira’, ‘Emma’, ‘Trisha’]
Результат:

Идеальные пары:
Alex и Emma
Arthur и Kate
John и Kira
Peter и Liza
Richard и Trisha
boys = [‘Peter’, ‘Alex’, ‘John’, ‘Arthur’, ‘Richard’, ‘Michael’]
girls = [‘Kate’, ‘Liza’, ‘Kira’, ‘Emma’, ‘Trisha’]
Результат:
Внимание, кто-то может остаться без пары!

### Решение

In [10]:
boys = ['Peter', 'Alex', 'John', 'Arthur', 'Richard']
girls = ['Kate', 'Liza', 'Kira', 'Emma', 'Trisha']

if len(boys) == len(girls):
    boys_by_girls = zip(sorted(boys), sorted(girls))
    print('Идеальные пары:')
    for couples in boys_by_girls:
        print(couples[0], 'и',couples[1])
else:
    print('Внимание, кто-то может остаться без пары!')

Идеальные пары:
Alex и Emma
Arthur и Kate
John и Kira
Peter и Liza
Richard и Trisha


In [11]:
boys = ['Peter', 'Alex', 'John', 'Arthur', 'Richard', 'Michael']
girls = ['Kate', 'Liza', 'Kira', 'Emma', 'Trisha']

if len(boys) == len(girls):
    boys_by_girls = zip(sorted(boys), sorted(girls))
    print('Идеальные пары:')
    for couples in boys_by_girls:
        print(couples[0], 'и',couples[1])
else:
    print('Внимание, кто-то может остаться без пары!')

Внимание, кто-то может остаться без пары!


### Задание 4
У нас есть список, содержащий информацию о среднедневной температуре в Фаренгейтах за произвольный период по странам (структура данных в примере). Необходимо написать код, который рассчитает среднюю температуру за период в Цельсиях(!) для каждой страны.

Пример работы программы:

countries_temperature = [
[‘Thailand’, [75.2, 77, 78.8, 73.4, 68, 75.2, 77]],
[‘Germany’, [57.2, 55.4, 59, 59, 53.6]],
[‘Russia’, [35.6, 37.4, 39.2, 41, 42.8, 39.2, 35.6]],
[‘Poland’, [50, 50, 53.6, 57.2, 55.4, 55.4]]
]
Результат:

Средняя температура в странах:
Thailand - 23.9 С
Germany - 13.8 С
Russia - 3.7 С
Poland - 12.0 С

### Решение

In [12]:
countries_temperature = [
['Thailand', [75.2, 77, 78.8, 73.4, 68, 75.2, 77]],
['Germany', [57.2, 55.4, 59, 59, 53.6]],
['Russia', [35.6, 37.4, 39.2, 41, 42.8, 39.2, 35.6]],
['Poland', [50, 50, 53.6, 57.2, 55.4, 55.4]]
]

print('Средняя температура в странах')
for temperature in countries_temperature:
        print(temperature[0], ' - ', round((sum(temperature[1])/len(temperature[1])-32)/1.8, 2), ' C ')

Средняя температура в странах
Thailand  -  23.86  C 
Germany  -  13.8  C 
Russia  -  3.71  C 
Poland  -  12.0  C 


### Задание 5
Дан поток логов по количеству просмотренных страниц для каждого пользователя. Вам необходимо написать алгоритм, который считает среднее значение просмотров на пользователя. Т. е. надо посчитать отношение суммы всех просмотров к количеству уникальных пользователей.

Примеры работы программы:

stream = [
‘2018-01-01,user1,3’,
‘2018-01-07,user1,4’,
‘2018-03-29,user1,1’,
‘2018-04-04,user1,13’,
‘2018-01-05,user2,7’,
‘2018-06-14,user3,4’,
‘2018-07-02,user3,10’,
‘2018-03-21,user4,19’,
‘2018-03-22,user4,4’,
‘2018-04-22,user4,8’,
‘2018-05-03,user4,9’,
‘2018-05-11,user4,11’,
]
Результат:
Среднее количество просмотров на уникального пользователя: 23.25

stream = [
‘2018-01-01,user100,150’,
‘2018-01-07,user99,205’,
‘2018-03-29,user1001,81’
]
Результат:
Среднее количество просмотров на уникального пользователя: 145.33

### Решение

In [13]:
stream = [
'2018-01-01,user1,3',
'2018-01-07,user1,4',
'2018-03-29,user1,1',
'2018-04-04,user1,13',
'2018-01-05,user2,7',
'2018-06-14,user3,4',
'2018-07-02,user3,10',
'2018-03-21,user4,19',
'2018-03-22,user4,4',
'2018-04-22,user4,8',
'2018-05-03,user4,9',
'2018-05-11,user4,11',
]

res_1 = []  # первый результирующий список, через оператор for применяем split ко всем строкам в списке
for element in stream:
    c = element.split(",")
    res_1.append(c)
res_2 = [] # второй результирующий список, выводим в него количество просмотров и считаем сумму всех просмотров пользователей
for scan in res_1:
    res_2.append(int(scan[2])) #приводим к типу integer, чтобы затем получить сумму
sum_ = sum(res_2)
res_3 = [] 
""" третий результирующий список, в него мы выводим всех пользователей которые делали просмотры по дням, 
то есть на выходе у нас просто список пользователей, количество строк по сути равно количеству дней, 
в которые были просмотры"""
for user in res_1:
        res_3.append(user[1])
res_4 = [] # четвертый результирующий список, в него выводим только уникальных пользователей
for user_ in res_3:
    if user_ not in res_4:
        res_4.append(user_)
#print(len(res_4))
print('Среднее количество просмотров на уникального пользователя: ', round(sum_/int(len(res_4)), 2)) 

Среднее количество просмотров на уникального пользователя:  23.25


In [17]:
# задание № 5 часть 2, проверка нашего решения

stream = [
'2018-01-01,user100,150',
'2018-01-07,user99,205',
'2018-03-29,user1001,81'
]

res_1 = []  # первый результирующий список, через оператор for применяем split ко всем строкам в списке
for element in stream:
    c = element.split(",")
    res_1.append(c)
#res_1
res_2 = [] # второй результирующий список, выводим в него количество просмотров и считаем сумму всех просмотров пользователей
for scan in res_1:
    res_2.append(int(scan[2])) #приводим к типу integer, чтобы затем получить сумму
sum_ = sum(res_2)
#sum_
res_3 = [] 
""" третий результирующий список, в него мы выводим всех пользователей которые делали просмотры по дням, 
то есть на выходе у нас просто список пользователей, количество строк по сути равно количеству дней, 
в которые были просмотры"""
for user in res_1:
        res_3.append(user[1])
res_3
res_4 = [] # четвертый результирующий список, в него выводим только уникальных пользователей
for user_ in res_3:
    if user_ not in res_4:
        res_4.append(user_)
#print(len(res_4))
print('Среднее количество просмотров на уникального пользователя: ', round(sum_/int(len(res_4)), 2))

Среднее количество просмотров на уникального пользователя:  145.33


### Задание 6
Необходимо у пользователя запрашивать набор чисел разделенных пробелом. В результате должны выводиться числа, которые повторяются в вводе более одного раза.

Примеры работы программы:

Введите числа:
4 8 0 3 4 2 0 3
Результат:
0 3 4

Введите числа:
1 1 2 2 3 3
Результат:
1 2 3

Введите числа:
1 1 1 1 1 2 2 2
Результат:
1 2

### Решение

In [16]:
user_input = str(input('Введите набор числе разделенных пробелом'))
my_list = user_input.split()
res = []
for element in my_list:
    if my_list.count(element) > 1 and element not in res:
        res.append(element)
print(' '.join(res))

Введите набор числе разделенных пробелом1 2 2 0 4 3 5
2


### Задание 7
Дана переменная, в которой хранится словарь, содержащий гео-метки для каждого пользователя (пример структуры данных приведен ниже). Вам необходимо написать программу, которая выведет на экран множество уникальных гео-меток всех пользователей.

Пример работы программы:

ids = {‘user1’: [213, 213, 213, 15, 213],
‘user2’: [54, 54, 119, 119, 119],
‘user3’: [213, 98, 98, 35]}
Результат: {98, 35, 15, 213, 54, 119}

### Решение

In [18]:
ids = {'user1': [213, 213, 213, 15, 213],
'user2': [54, 54, 119, 119, 119],
'user3': [213, 98, 98, 35]}

a = []
b = list(ids.values())
for metric in b:
       a.extend(metric)
print('Результат: ', set(a))

Результат:  {98, 35, 15, 213, 54, 119}


In [19]:
ids = {'user1': [213, 213, 213, 15, 213],
'user2': [54, 54, 119, 119, 119],
'user3': [213, 98, 98, 35]}

a = set()
for value in ids.values():
    a = a.union(set(value))
print('Результаты: ', a)

Результаты:  {98, 35, 213, 54, 119, 15}


### Задание 8
Дана переменная, в которой хранится список поисковых запросов пользователя (пример структуры данных приведен ниже). Вам необходимо написать программу, которая выведет на экран распределение количества слов в запросах в требуемом виде.

Пример работы программы:

queries = [
‘смотреть сериалы онлайн’,
‘новости спорта’,
‘афиша кино’,
‘курс доллара’,
‘сериалы этим летом’,
‘курс по питону’,
‘сериалы про спорт’,
]
Результат:

Поисковых запросов, содержащих 2 слов(а): 42.86%
Поисковых запросов, содержащих 3 слов(а): 57.14%

### Решение

In [26]:
queries = ['смотреть сериалы онлайн',
'новости спорта',
'афиша кино',
'курс доллара',
'сериалы этим летом',
'курс по питону',
'сериалы про спорт',
]


res = {}
for scan in queries:
    length = len(scan.split())
    res.setdefault(length, 0)
    res[length] += 1
for key, value in res.items():
    print(f'Поисковых запросов, содержащих {value} слов(а): {round(value/len(queries)*100, 2)} %')

Поисковых запросов, содержащих 4 слов(а): 57.14 %
Поисковых запросов, содержащих 3 слов(а): 42.86 %


### Задание 9
Дана переменная, в которой хранится информация о затратах и доходе рекламных кампаний по различным источникам. Необходимо дополнить исходную структуру показателем ROI, который рассчитаем по формуле: (revenue / cost - 1) * 100

Пример работы программы:

results = {
‘vk’: {‘revenue’: 103, ‘cost’: 98},
‘yandex’: {‘revenue’: 179, ‘cost’: 153},
‘facebook’: {‘revenue’: 103, ‘cost’: 110},
‘adwords’: {‘revenue’: 35, ‘cost’: 34},
‘twitter’: {‘revenue’: 11, ‘cost’: 24},
}
Результат:

{‘adwords’: {‘ROI’: 2.94, ‘cost’: 34, ‘revenue’: 35},
‘facebook’: {‘ROI’: -6.36, ‘cost’: 110, ‘revenue’: 103},
‘twitter’: {‘ROI’: -54.17, ‘cost’: 24, ‘revenue’: 11},
‘vk’: {‘ROI’: 5.1, ‘cost’: 98, ‘revenue’: 103},
‘yandex’: {‘ROI’: 16.99, ‘cost’: 153, ‘revenue’: 179}}

### Решение

In [21]:
results = {
'vk': {'revenue': 103, 'cost': 98},
'yandex': {'revenue': 179, 'cost': 153},
'facebook': {'revenue': 103, 'cost': 110},
'adwords': {'revenue': 35, 'cost': 34},
'twitter': {'revenue': 11, 'cost': 24},
}


for network, ROI in results.items():
    ROI_ = round((ROI['revenue']/ROI['cost']-1)*100, 2)
    ROI['ROI'] = ROI_

results

{'vk': {'revenue': 103, 'cost': 98, 'ROI': 5.1},
 'yandex': {'revenue': 179, 'cost': 153, 'ROI': 16.99},
 'facebook': {'revenue': 103, 'cost': 110, 'ROI': -6.36},
 'adwords': {'revenue': 35, 'cost': 34, 'ROI': 2.94},
 'twitter': {'revenue': 11, 'cost': 24, 'ROI': -54.17}}

In [23]:
# сортировка источников

results = {
'vk': {'revenue': 103, 'cost': 98},
'yandex': {'revenue': 179, 'cost': 153},
'facebook': {'revenue': 103, 'cost': 110},
'adwords': {'revenue': 35, 'cost': 34},
'twitter': {'revenue': 11, 'cost': 24},
}


for network, ROI in results.items():
    ROI_ = round((ROI['revenue']/ROI['cost']-1)*100, 2)
    ROI['ROI'] = ROI_


list_keys_2 = list(results.keys())
list_keys_2.sort()
for i_2 in list_keys_2:
    print(i_2, ':', results[i_2])

adwords : {'revenue': 35, 'cost': 34, 'ROI': 2.94}
facebook : {'revenue': 103, 'cost': 110, 'ROI': -6.36}
twitter : {'revenue': 11, 'cost': 24, 'ROI': -54.17}
vk : {'revenue': 103, 'cost': 98, 'ROI': 5.1}
yandex : {'revenue': 179, 'cost': 153, 'ROI': 16.99}


### Задание 10
Дана переменная, в которой хранится статистика рекламных каналов по объемам продаж (пример структуры данных приведен ниже). Напишите программу, которая возвращает название канала с максимальным объемом продаж.

Пример работы программы:

stats = {‘facebook’: 55, ‘yandex’: 115, ‘vk’: 120, ‘google’: 99, ‘email’: 42, ‘ok’: 98}

Результат: Максимальный объем продаж на рекламном канале: vk

In [24]:
stats = {'facebook': 55, 'yandex': 115, 'vk': 120, 'google': 99, 'email': 42, 'ok': 98}

max_value = max((stats.values()))
final_dict = {key:value for key, value in stats.items() if value == max_value}
a = list(final_dict.keys())
print('Максимальный объем продаж на рекламном канале: ', a[0])

Максимальный объем продаж на рекламном канале:  vk


### Задание 11
Дана книга рецептов с информацией о том, сколько ингредиентов нужно для приготовления блюда в расчете на одну порцию (пример данных представлен ниже).
Напишите программу, которая будет запрашивать у пользователя количество порций для приготовления этих блюд и отображать информацию о суммарном количестве требуемых ингредиентов в указанном виде.

Пример работы программы:

cook_book = {
‘салат’: [
{‘ingridient_name’: ‘сыр’, ‘quantity’: 50, ‘measure’: ‘гр’},
{‘ingridient_name’: ‘томаты’, ‘quantity’: 2, ‘measure’: ‘шт’},
{‘ingridient_name’: ‘огурцы’, ‘quantity’: 20, ‘measure’: ‘гр’},
{‘ingridient_name’: ‘маслины’, ‘quantity’: 10, ‘measure’: ‘гр’},
{‘ingridient_name’: ‘оливковое масло’, ‘quantity’: 20, ‘measure’: ‘мл’},
{‘ingridient_name’: ‘салат’, ‘quantity’: 10, ‘measure’: ‘гр’},
{‘ingridient_name’: ‘перец’, ‘quantity’: 20, ‘measure’: ‘гр’}
],
‘пицца’: [
{‘ingridient_name’: ‘сыр’, ‘quantity’: 20, ‘measure’: ‘гр’},
{‘ingridient_name’: ‘колбаса’, ‘quantity’: 30, ‘measure’: ‘гр’},
{‘ingridient_name’: ‘бекон’, ‘quantity’: 30, ‘measure’: ‘гр’},
{‘ingridient_name’: ‘оливки’, ‘quantity’: 10, ‘measure’: ‘гр’},
{‘ingridient_name’: ‘томаты’, ‘quantity’: 20, ‘measure’: ‘гр’},
{‘ingridient_name’: ‘тесто’, ‘quantity’: 100, ‘measure’: ‘гр’},
],
‘лимонад’: [
{‘ingridient_name’: ‘лимон’, ‘quantity’: 1, ‘measure’: ‘шт’},
{‘ingridient_name’: ‘вода’, ‘quantity’: 200, ‘measure’: ‘мл’},
{‘ingridient_name’: ‘сахар’, ‘quantity’: 10, ‘measure’: ‘гр’},
{‘ingridient_name’: ‘лайм’, ‘quantity’: 20, ‘measure’: ‘гр’},
]
}

Введите количество порций:
3
Результат:

Сыр: 210 гр
Томаты: 6 шт
Огурцы: 60 гр
Маслины: 30 гр
Оливковое Масло: 60 мл
Салат: 30 гр
Перец: 60 гр
Колбаса: 90 гр
Бекон: 90 гр
Оливки: 30 гр
Томаты: 60 гр
Тесто: 300 гр
Лимон: 3 шт
Вода: 600 мл
Сахар: 30 гр
Лайм: 60 гр

### Решение

In [27]:
cook_book = {
'салат': [
{'ingridient_name': 'сыр', 'quantity': 50, 'measure': 'гр'},
{'ingridient_name': 'томаты', 'quantity': 20, 'measure': 'гр'},
{'ingridient_name': 'огурцы', 'quantity': 20, 'measure': 'гр'},
{'ingridient_name': 'маслины', 'quantity': 10, 'measure': 'гр'},
{'ingridient_name': 'оливковое масло', 'quantity': 20, 'measure': 'мл'},
{'ingridient_name': 'салат', 'quantity': 10, 'measure': 'гр'},
{'ingridient_name': 'перец', 'quantity': 20, 'measure': 'гр'}
],
'пицца': [
{'ingridient_name': 'сыр', 'quantity': 20, 'measure': 'гр'},
{'ingridient_name': 'колбаса', 'quantity': 30, 'measure': 'гр'},
{'ingridient_name': 'бекон', 'quantity': 30, 'measure': 'гр'},
{'ingridient_name': 'оливки', 'quantity': 10, 'measure': 'гр'},
{'ingridient_name': 'томаты', 'quantity': 20, 'measure': 'гр'},
{'ingridient_name': 'тесто', 'quantity': 100, 'measure': 'гр'},
],
'лимонад': [
{'ingridient_name': 'лимон', 'quantity': 1, 'measure': 'шт'},
{'ingridient_name': 'вода', 'quantity': 200, 'measure': 'мл'},
{'ingridient_name': 'сахар', 'quantity': 10, 'measure': 'гр'},
{'ingridient_name': 'лайм', 'quantity': 20, 'measure': 'гр'},
]
}

res = {}
x=int(input('Введите количество порций'))
print('Результат:')
for dish in cook_book.values():
    for ingridient in dish:
        if (ingridient['ingridient_name'], ingridient['measure']) not in res:
            res[(ingridient['ingridient_name'], ingridient['measure'])] = ingridient['quantity']
        else:
            res[(ingridient['ingridient_name'], ingridient['measure'])] += ingridient['quantity']
for a, b in res.items():
        list_a = list(a)
        product = list_a[0]
        measure = list_a[1]
        count = b * x 
        print(f'{product.capitalize()}: {count} {measure}')


Введите количество порций3
Результат:
Сыр: 210 гр
Томаты: 120 гр
Огурцы: 60 гр
Маслины: 30 гр
Оливковое масло: 60 мл
Салат: 30 гр
Перец: 60 гр
Колбаса: 90 гр
Бекон: 90 гр
Оливки: 30 гр
Тесто: 300 гр
Лимон: 3 шт
Вода: 600 мл
Сахар: 30 гр
Лайм: 60 гр


### Задание 12
Дан список произвольной длины. Необходимо написать код, который на основе исходного списка составит словарь такого уровня вложенности, какова длина исхондого списка.

Примеры работы программы:

my_list = [‘2018-01-01’, ‘yandex’, ‘cpc’, 100]
Результат: {‘2018-01-01’: {‘yandex’: {‘cpc’: 100}}}

my_list = [‘a’, ‘b’, ‘c’, ‘d’, ‘e’, ‘f’]
Результат: {‘a’: {‘b’: {‘c’: {‘d’: {‘e’: ‘f’}}}}}

### Решение

In [29]:
my_list = ['2018-01-01', 'yandex', 'cpc', 100]
res = my_list[-1]            
for el in reversed(my_list[:-1]):      
    res = {el: res}
print(res)

{'2018-01-01': {'yandex': {'cpc': 100}}}


# Функции

### Предусловие
Вам нужно помочь секретарю автоматизировать работу. Для этого нужно написать программу, которая будет на основе хранимых данных исполнять пользовательские команды.

Исходные данные имеют следующую структуру:

1. перечень всех документов

documents = [
{‘type’: ‘passport’, ‘number’: ‘2207 876234’, ‘name’: ‘Василий Гупкин’},
{‘type’: ‘invoice’, ‘number’: ‘11-2’, ‘name’: ‘Геннадий Покемонов’},
{‘type’: ‘insurance’, ‘number’: ‘10006’, ‘name’: ‘Аристарх Павлов’}
]

2.перечень полок, на которых хранятся документы (если документ есть в documents, то он обязательно должен быть и в directories)

directories = {
‘1’: [‘2207 876234’, ‘11-2’],
‘2’: [‘10006’],
‘3’: []
}

Общие требования к программе:

код должен быть грамотно декомпозирован (каждая функция отвечает за свою конкретную задачу, дублирующийся функционал переиспользуется, а его код не повторяется);
в коде отсутствуют глобальные переменные (за исключением documents и directories);
пользовательский ввод обрабатывается в цикле while до тех пор, пока пользователь явно не завершит программу (вводом команды “q”).


### Задание 1
Пункт 1. Пользователь по команде “p” может узнать владельца документа по его номеру
Примеры работы:

Введите команду:
p

Введите номер документа:
10006

Результат:
Владелец документа: Аристарх Павлов

Введите команду:
p

Введите номер документа:
12345

Результат:
Документ не найден в базе

Пункт 2. Пользователь по команде “s” может по номеру документа узнать на какой полке он хранится
Примеры работы:

Введите команду:
s

Введите номер документа:
10006

Результат:
Документ хранится на полке: 2

Введите команду:
p

Введите номер документа:
12345

Результат:
Документ не найден в базе

Пункт 3. Пользователь по команде “l” может увидеть полную информацию по всем документам
Пример работы:

Введите команду:
l
Результат:

№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
Пункт 4. Пользователь по команде “as” может добавить новую полку
Примеры работы:

Введите команду:
as

Введите номер полки:
10

Результат:
Полка добавлена. Текущий перечень полок: 1, 2, 3, 10.

Введите команду:
as

Введите номер полки:
1

Результат:
Такая полка уже существует. Текущий перечень полок: 1, 2, 3.

Пункт 5. Пользователь по команде “ds” может удалить существующую полку из данных (только если она пустая)
Примеры работы:

Введите команду:
ds

Введите номер полки:
3
Результат:
Полка удалена. Текущий перечень полок: 1, 2.

Введите команду:
ds

Введите номер полки:
1
Результат:
На полке есть документа, удалите их перед удалением полки. Текущий перечень полок: 1, 2, 3.

Введите команду:
ds

Введите номер полки:
4
Результат:
Такой полки не существует. Текущий перечень полок: 1, 2, 3.

### Решение

In [30]:
documents = [
 {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
 {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
 {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]

In [31]:
directories = {
 '1': ['2207 876234', '11-2'],
 '2': ['10006'],
 '3': []
}  

In [32]:
def name_owner():
    user_input = input('Введите номер документа')
    for document in documents:
        number = document['number']
        name = document['name']
        if user_input == number:
            a = name
            break
        else:
            a = None
    if a != None:
        print('Владелец документа:', a)
    else:
        print('Владелец документа не найден')

name_owner()

Введите номер документа11-2
Владелец документа: Геннадий Покемонов


In [34]:
def number_directory():
    user_input = input('Введите номер документа')
    for key, value in directories.items():
        if user_input in value:
            el = key
            break
        else:
            el = None
    if el != None:
        print('Документ хранится на полке', el)
    else:
        print('Документ не найден или некорретный номер документа')
        
number_directory()

Введите номер документа10006
Документ хранится на полке 2


In [35]:
def info_total():
    for document in documents:
                type_doc = document['type']
                doc_num = document['number']
                name_own =  document['name']
                for key, value in directories.items():
                    if document['number'] in value:
                        x = key
                print('№:', doc_num, ',', 'тип:', type_doc, ',', 'владелец:', name_own, 'полка хранения:', x)
                
info_total()

№: 2207 876234 , тип: passport , владелец: Василий Гупкин полка хранения: 1
№: 11-2 , тип: invoice , владелец: Геннадий Покемонов полка хранения: 1
№: 10006 , тип: insurance , владелец: Аристарх Павлов полка хранения: 2


In [36]:
def get_directory():
    user_input = input('Введите номер полки')
    for key in directories.keys():
        key
    if user_input not in directories:
        directories[user_input] = []
        print('Полка добавлена. Текущий перечень полок:', ', '.join(directories.keys()), '.')        
    else:
        print('Такая полка уже существует. Текущий перечень полок:', ', '.join(directories.keys()), '.')
    
get_directory()

Введите номер полки2
Такая полка уже существует. Текущий перечень полок: 1, 2, 3 .


In [43]:
def delete_directory():
    user_input = input('Введите номер полки')
    if user_input in list(directories.keys()) and directories[user_input] == [] :
        del(directories[user_input])
        print('Полка удалена.Текущий перечень полок:', ', '.join(directories.keys()), '.')
    elif user_input in list(directories.keys()) and directories[user_input] != [] :
        print('На полке есть документы, удалите их перед удалением полки.Текущий перечень полок:', ', '.join(directories.keys()), '.')
    else:
        print('Такой полки не существует. Текущий перечень полок:', ', '.join(directories.keys()), '.')
    

delete_directory()

Введите номер полки11
Такой полки не существует. Текущий перечень полок: 1, 2, 3 .


In [39]:
def main():
    print('Результат:')
    while True:
        user_input = input('Введите команду')
        if user_input == 'p':
                name_owner()
        elif user_input == 's':
            number_directory()
        elif user_input == 'l':
            info_total()
        elif user_input == 'ads':
            get_directory()
        elif user_input == 'ds':
            delete_directory()
        elif user_input == 'ad':
            get_document()
        elif user_input == 'd':
            delete_document()
        elif user_input == 'm':
                move_doc()
        elif user_input == 'q':
            print('Работа завершена')
            break
        else:
            print('Введена неверная команда')

In [41]:
main()

Результат:
Введите командуl
№: 2207 876234 , тип: passport , владелец: Василий Гупкин полка хранения: 1
№: 11-2 , тип: invoice , владелец: Геннадий Покемонов полка хранения: 1
№: 10006 , тип: insurance , владелец: Аристарх Павлов полка хранения: 2
Введите командуq
Работа завершена


### Задание 2
Вам необходимо дополнить программу из задания 1 более продвинутыми командами.

Пункт 1. Пользователь по команде “ad” может добавить новый документ в данные
Примеры работы:

Введите команду:
ad

Введите номер документа:
42
Введите тип документа:
multipassport
Введите владельца документа:
R2D2
Введите полку для хранения:
3

Результат:

Документ добавлен. Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
№: 42, тип: multipassport, владелец: R2D2, полка хранения: 3

Введите команду:
ad

Введите номер документа:
42
Введите тип документа:
multipassport
Введите владельца документа:
R2D2
Введите полку для хранения:
4

Результат:

Такой полки не существует. Добавьте полку командой as.
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2

Пункт 2. Пользователь по команде “d” может удалить документ из данных
Примеры работы:

Введите команду:
d

Введите номер документа:
10006

Результат:

Документ удален.
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1

Введите команду:
d

Введите номер документа:
123456

Результат:

Документ не найден в базе.
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2

Пункт 3. Пользователь по команде “m” может переместить документ с полки на полку
Примеры работы:

Введите команду:
m

Введите номер документа:
11-2
Введите номер полки:
3

Результат:

Документ перемещен.
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2

Введите команду:
m

Введите номер документа:
11-2
Введите номер полки:
10

Результат:
Такой полки не существует. Текущий перечень полок: 1, 2, 3.

Введите команду:
m

Введите номер документа:
42
Введите номер полки:
2

Результат:

Документ не найден в базе.
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2

### Решение

In [42]:
def get_document():
    user_input = input('Введите номер документа: ')
    a = user_input
    user_input_2 = input('Введите тип документа: ')
    b = user_input_2
    user_input_3 = input('Введите владельца документа: ')
    c = user_input_3
    user_input_key = input('Введите полку для хранения: ')
    key = user_input_key
    if key in directories.keys():
        res = {}
        res['type'] = b
        res['number'] = a
        res['name'] = c
        documents.append(res)
        directories[key].append(a)
        print('Документ добавлен. Текущий список документов:')
        info_total()
    else:
        print('Такой полки не существует. Добавьте полку командой as.')
        info_total()
        
get_document()

Введите номер документа: 44
Введите тип документа: вид на жительство
Введите владельца документа: Иванова Иванна Петровна
Введите полку для хранения: 3
Документ добавлен. Текущий список документов:
№: 2207 876234 , тип: passport , владелец: Василий Гупкин полка хранения: 1
№: 11-2 , тип: invoice , владелец: Геннадий Покемонов полка хранения: 1
№: 10006 , тип: insurance , владелец: Аристарх Павлов полка хранения: 2
№: 44 , тип: вид на жительство , владелец: Иванова Иванна Петровна полка хранения: 3


In [44]:
def delete_document():
    user_input = input('Введите номер документа')
    for value in documents:
        if user_input in list(value.values()):
            documents.remove(value)
            print('Документ удален.')
            print('Текущий список документов:')
            info_total()
            return
    for key, value in directories.items():
        if user_input in value:
            value.remove(user_input)
            return
    print('Документ не найден в базе.')
    print('Текущий список документов:')
    info_total()
    return
    
                   
delete_document()

Введите номер документа44
Документ удален.
Текущий список документов:
№: 2207 876234 , тип: passport , владелец: Василий Гупкин полка хранения: 1
№: 11-2 , тип: invoice , владелец: Геннадий Покемонов полка хранения: 1
№: 10006 , тип: insurance , владелец: Аристарх Павлов полка хранения: 2


In [45]:
def move_doc():
    doc_number = input('Введите номер документа: ')
    number_directory = input('Введите номер полки:')
    if number_directory not in directories:
        print('Такой полки не существует. Текущий перечень полок:', ', '.join(directories.keys()), '.')
        return
    for key, value in directories.items():
        if doc_number in value:
            directories[number_directory] += [doc_number]
            value.remove(doc_number)
            print('Документ перемещен')
            print('Текущий список документов:')
            info_total()
            return
    print('Документ не найден в базе.')
    print('Текущий список документов:')
    info_total()
    return

move_doc()

Введите номер документа: 11-2
Введите номер полки:1
Документ перемещен
Текущий список документов:
№: 2207 876234 , тип: passport , владелец: Василий Гупкин полка хранения: 1
№: 11-2 , тип: invoice , владелец: Геннадий Покемонов полка хранения: 1
№: 10006 , тип: insurance , владелец: Аристарх Павлов полка хранения: 2


# Работа с файловой системой и модули

### Задание 1

Переведите содержимое файла purchase_log.txt в словарь purchases вида:
{‘1840e0b9d4’: ‘Продукты’, …}

Для каждого user_id в файле visit_log.csv определите третий столбец с категорией покупки (если покупка была, сам файл visit_log.csv изменять не надо). Запишите в файл funnel.csv визиты из файла visit_log.csv, в которых были покупки с указанием категории.
Учтите условия на данные:
содержимое purchase_log.txt помещается в оперативную память компьютера
содержимое visit_log.csv - нет; используйте только построчную обработку этого файла

### Решение

In [46]:
import json

In [48]:
purchases = {}
i = 0
with open('C:/Netology/purchase_log.txt', encoding='utf-8') as f:
    first_line = f.readline()
    my_first_line = json.loads(first_line)
    for line in f:
        my_dict = json.loads(line)
        key = my_dict['user_id']
        value = my_dict['category']
        purchases[key] = value

In [49]:
a = 0
for key in purchases:
    print(key)
    a += 1
    if a > 4:
        break

1840e0b9d4
4e4f90fcfb
afea8d72fc
373a6055fe
9b2ab046f3


In [51]:
i = 0
for key, value in purchases.items():
    print(key, value)
    i += 1
    if i > 10:
        break

1840e0b9d4 Продукты
4e4f90fcfb Электроника
afea8d72fc Электроника
373a6055fe Бытовая техника
9b2ab046f3 Электроника
9f39d307c3 Электроника
44edeffc91 Продукты
704474fa2d Продукты
1de31be403 Бытовая техника
b71f36a5e4 Продукты
79843a685a Продукты


In [52]:
len(purchases)

99517

In [54]:
i_2 = 0
with open('C:/Netology/visit_log.csv', 'r') as file_2:
    for line_2 in file_2:
        my_list = line_2.strip().split(',')
        for key, value in purchases.items():
            if key == my_list[0] :
                my_list.append(value)
                print(my_list)
                i_2 += 1
        if i_2 > 5:
            break

['1840e0b9d4', 'other', 'Продукты']
['4e4f90fcfb', 'context', 'Электроника']
['afea8d72fc', 'other', 'Электроника']
['2824221f38', 'email', 'Продукты']
['373a6055fe', 'other', 'Бытовая техника']
['9b2ab046f3', 'other', 'Электроника']


In [55]:
a = 0
for key, value in purchases.items():
        print(key, value)
        a += 1
        if a > 5:
            break

1840e0b9d4 Продукты
4e4f90fcfb Электроника
afea8d72fc Электроника
373a6055fe Бытовая техника
9b2ab046f3 Электроника
9f39d307c3 Электроника


In [56]:
print(type(purchases))

<class 'dict'>


### Задание 2
Для каждого user_id в файле visit_log.csv определите третий столбец с категорией покупки (если покупка была, сам файл visit_log.csv изменять не надо). Запишите в файл funnel.csv визиты из файла visit_log.csv, в которых были покупки с указанием категории.
Учтите условия на данные:
содержимое purchase_log.txt помещается в оперативную память компьютера
содержимое visit_log.csv - нет; используйте только построчную обработку этого файла

### Решение

In [58]:
import csv
with open('C:/Netology/visit_log.csv', 'r') as file_2:
    with open('C:/Netology/Portfolio/funnel.csv', 'w', encoding='utf-8') as file_write:
        for line_2 in file_2:
            el = line_2.strip().split(',')
            if  my_first_line['user_id'] == el[0]:
                a = my_first_line['category']
                file_write.write(f'{el[0]},{el[1]},{a}\n')
            elif purchases.get(el[0]) != None and el[1] != None:
                b =  purchases.get(el[0])
                file_write.write(f'{el[0]},{el[1]},{b}\n')

# Исключения и обработка ошибок

### Задание 1
Печатные газеты использовали свой формат дат для каждого выпуска. Для каждой газеты из списка напишите формат указанной даты для перевода в объект datetime:
The Moscow Times - Wednesday, October 2, 2002
The Guardian - Friday, 11.10.13
Daily News - Thursday, 18 August 1977

### Решение

In [60]:
from datetime import datetime

In [62]:
#The Moscow Times - Wednesday, October 2, 2002
#The Guardian - Friday, 11.10.13
#Daily News - Thursday, 18 August 1977

newspaper_name_1 = 'The Moscow Times'
newspaper_name_2 = 'The Guardian'
newspaper_name_3 = 'Daily News'
newspaper_date_1 = 'Wednesday, October 2, 2002'
newspaper_date_2 = 'Friday, 11.10.13'
newspaper_date_3 = 'Thursday, 18 August 1977'

datetime_1 = datetime.strptime(newspaper_date_1, '%A, %B %d, %Y')
datetime_2 = datetime.strptime(newspaper_date_2, '%A, %d.%m.%y')
datetime_3 = datetime.strptime(newspaper_date_3, '%A, %d %B %Y')

print(f'{newspaper_name_1} - {datetime_1}')
print(f'{newspaper_name_2} - {datetime_2}')
print(f'{newspaper_name_3} - {datetime_3}')

The Moscow Times - 2002-10-02 00:00:00
The Guardian - 2013-10-11 00:00:00
Daily News - 1977-08-18 00:00:00


### Задание 2
Дан поток дат в формате YYYY-MM-DD, в которых встречаются некорректные значения:
stream = [‘2018-04-02’, ‘2018-02-29’, ‘2018-19-02’]

Напишите функцию, которая проверяет эти даты на корректность. Т. е. для каждой даты возвращает True (дата корректна) или False (некорректная дата).

### Решение

In [68]:
stream = ['2018-04-02', '2018-02-29', '2018-19-02']

for line in stream:
    try:
        line_date = datetime.strptime(line, '%Y-%m-%d')
        print (True, 'дата корректна')
    except:
        print (False, 'некорректная дата')

True дата корректна
False некорректная дата
False некорректная дата


### Задание 3
Напишите функцию date_range, которая возвращает список дат за период от start_date до end_date. Даты должны вводиться в формате YYYY-MM-DD. В случае неверного формата или при start_date > end_date должен возвращаться пустой список.

### Решение

In [67]:
from datetime import timedelta

def date_range():
    date_list = []
    start_date = input('Введите дату в формате YYYY-MM-DD: ')
    end_date = input('Введите дату в формате YYYY-MM-DD: ')
    try:
        start_date_dt = datetime.strptime(start_date, '%Y-%m-%d')
        end_date_dt = datetime.strptime(end_date, '%Y-%m-%d')
    except ValueError: 
        print('Некорретный ввод')
        return(date_list)
        
    if start_date < end_date:
        date_list = [(start_date_dt + timedelta(days = x)).strftime('%Y-%m-%d') for x in range(0, (end_date_dt - start_date_dt).days)]
        date_list.append(end_date_dt.strftime('%Y-%m-%d'))
        print('\n'.join(date_list))
    elif start_date > end_date:
        print('Некорретный ввод')
        print(date_list) 
    elif start_date == end_date:
        start_date_dt = datetime.strptime(start_date, '%Y-%m-%d')
        end_date_dt = datetime.strptime(end_date, '%Y-%m-%d')
        date_list.append(start_date_dt.strftime('%Y-%m-%d'))
        print(date_list)
    else:
        print('Некорретный ввод')
        print(date_list)
        
       
date_range()

Введите дату в формате YYYY-MM-DD: 2020-12-13
Введите дату в формате YYYY-MM-DD: 13-12-2020
Некорретный ввод


[]

### Задание 4
Ваш коллега прислал код функции:

DEFAULT_USER_COUNT = 3

def delete_and_return_last_user(region, default_list=[‘A100’, ‘A101’, ‘A102’]):
""“
Удаляет из списка default_list последнего пользователя
и возвращает ID нового последнего пользователя.
”""
element_to_delete = default_list[-1]
default_list.remove(element_to_delete)

return default_list[DEFAULT_USER_COUNT-2]
При однократном вызове этой функции все работает корректно:
delete_and_return_last_user(1)
‘A101’

Однако, при повторном вызове получается ошибка IndexError: list index out of range.

Задание:

Что значит ошибка list index out of range?
Почему при первом запуске функция работает корректно, а при втором - нет?

### Решение

In [65]:
DEFAULT_USER_COUNT = 3

def delete_and_return_last_user(region, default_list=['A100', 'A101', 'A102']):
    element_to_delete = default_list[-1]
    default_list.remove(element_to_delete)
    return default_list[DEFAULT_USER_COUNT-2]
    
delete_and_return_last_user(1)

'A101'

# Понятие класса

### Задание 1
Напишите функцию, которая возвращает название валюты (поле ‘Name’) с максимальным значением курса с помощью сервиса https://www.cbr-xml-daily.ru/daily_json.js

### Решение

In [72]:
import requests
    
def max_():
    """Возвращает название валюты с максимальным значением курса"""
    res = {}  #результирующий словарь в котором будут все валюты (ключ Name, значение Value)
    r = requests.get('https://www.cbr-xml-daily.ru/daily_json.js').json()
    """Раскладываем словари, чтобы добраться до Name и Value"""
    for char_code, value_1 in r['Valute'].items():
        for key, value_2 in value_1.items():  
            k = value_1['Name']
            v = value_1['Value']/value_1['Nominal']
            if k not in res:
                res[k] = v  #записываем данные в результирующий словарь
    max_val = max(res.values())   #максимальное значение в результирующем словаре
    """Находим ключ, соответсвующий максимальному значению, результат записываем в новый словарь"""
    final_dict = {k_:v_ for k_, v_ in res.items() if v_ == max_val} 
    return final_dict

In [73]:
max_()

{'СДР (специальные права заимствования)': 104.8153}

### Задание 2
Добавьте в класс Rate параметр diff (со значениями True или False), который в случае значения True в методах курсов валют (eur, usd итд) будет возвращать не курс валюты, а изменение по сравнению в прошлым значением. Считайте, self.diff будет принимать значение True только при возврате значения курса. При отображении всей информации о валюте он не используется.

### Решение

In [74]:
class Rate:
    def __init__(self, diff=True, format_='value'):
        self.format = format_
        self.diff = diff
    
    def exchange_rates(self):
        """
        Возвращает ответ сервиса с информацией о валютах в виде:
        
        {
            'AMD': {
                'CharCode': 'AMD',
                'ID': 'R01060',
                'Name': 'Армянских драмов',
                'Nominal': 100,
                'NumCode': '051',
                'Previous': 14.103,
                'Value': 14.0879
                },
            ...
        }
        """
        self.r = requests.get('https://www.cbr-xml-daily.ru/daily_json.js')
        return self.r.json()['Valute']
    
    def make_format(self, currency):
        """
        Возвращает информацию о валюте currency в двух вариантах:
        - полная информация о валюте при self.format = 'full':
        Rate('full').make_format('EUR')
        {
            'CharCode': 'EUR',
            'ID': 'R01239',
            'Name': 'Евро',
            'Nominal': 1,
            'NumCode': '978',
            'Previous': 79.6765,
            'Value': 79.4966
        }
        
        Rate('value').make_format('EUR')
        79.4966
        """
        response = self.exchange_rates()
        
        
        if currency in response:
            if self.format == 'full':
                return response[currency]
            
            # Задание № 2 добавление параметра diff
            if self.format == 'value':
                if self.diff == True: #условие значения для параметра diff
                    return round(response[currency]['Previous'] - response[currency]['Value'], 4) # разница между предудущим и текущим значением курса валюьы
                else:
                    return response[currency]['Value']
        
        return 'Error'
    
    def eur(self):
        """Возвращает курс евро на сегодня в формате self.format"""
        return self.make_format('EUR')
    
    def usd(self):
        """Возвращает курс доллара на сегодня в формате self.format"""
        return self.make_format('USD')
    
    def brl(self):
        """Возвращает курс бразильского реала на сегодня в формате self.format"""
        return self.make_format('BRL')
    
            

In [75]:
r = Rate(format_='full', diff=True)

In [76]:
r.usd()

{'ID': 'R01235',
 'NumCode': '840',
 'CharCode': 'USD',
 'Nominal': 1,
 'Name': 'Доллар США',
 'Value': 73.1195,
 'Previous': 73.7124}

In [77]:
r = Rate(diff=True)

In [78]:
r.brl()

-0.2938

In [79]:
r.eur()

0.3586

### Задание 3
Напишите класс Designer, который учитывает количество международных премий. Подсказки в коде занятия в разделе “Домашнее задание задача 3”.

Комментарий по классу Designer такой:
Напишите класс Designer, который учитывает количество международных премий для дизайнеров (из презентации: “Повышение на 1 грейд за каждые 7 баллов. Получение международной премии – это +2 балла”). Считайте, что при выходе на работу сотрудник уже имеет две премии и их количество не меняется со стажем (конечно если хотите это можно вручную менять).

### Решение

In [80]:
class Employee:
    def __init__(self, name, seniority):
        self.name = name
        self.seniority = seniority
        
        self.grade = 1
    
    def grade_up(self):
        """Повышает уровень сотрудника"""
        self.grade += 1
    
    def publish_grade(self):
        """Публикация результатов аккредитации сотрудников"""
        print(self.name, self.grade)
    
    def check_if_it_is_time_for_upgrade(self):
        pass

In [81]:
class Developer(Employee):
    def __init__(self, name, seniority):
        super().__init__(name, seniority)
    
    def check_if_it_is_time_for_upgrade(self):
        # для каждой аккредитации увеличиваем счетчик на 1
        # пока считаем, что все разработчики проходят аккредитацию
        self.seniority += 1
        
        # условие повышения сотрудника из презентации
        if self.seniority % 5 == 0:
            self.grade_up()
        
        # публикация результатов
        return self.publish_grade()

In [82]:
# проверяем как работает система повышения сотрудников на примере отдела разработки

# разработчик Александр только что пришел в компанию
alex = Developer('Александр', 0)

In [83]:
for i in range(20):
    alex.check_if_it_is_time_for_upgrade()

Александр 1
Александр 1
Александр 1
Александр 1
Александр 2
Александр 2
Александр 2
Александр 2
Александр 2
Александр 3
Александр 3
Александр 3
Александр 3
Александр 3
Александр 4
Александр 4
Александр 4
Александр 4
Александр 4
Александр 5


In [84]:
class Designer(Employee):
    def __init__(self, name, seniority, awards):
        super().__init__(name, seniority)
        self.awards = awards
    
    def check_if_it_is_time_for_upgrade(self):
        # для каждой аккредитации увеличиваем счетчик на 1
        # пока считаем, что все разработчики проходят аккредитацию
      
        
        # условие повышения сотрудника при наличии международной премии
        if self.awards != 0:
            for i in range(self.awards*2):
                self.seniority += 1   # повышаем баллы сотрудника n раз, где n = количество премий * количество баллов за одну премию
                if self.seniority % 7 == 0: # проверяем на кратность 7 по условию повышения грейда
                    self.grade_up()
                    self.awards = 0
                else:
                    self.awards = 0   #обнуляем количество премий чтобы их учесть разово на старте каррьеры 
        else:
            self.seniority += 1
            if self.seniority % 7 == 0:
                self.grade_up()
        
            
        # публикация результатов
        return self.publish_grade()

In [85]:
elena = Designer('Елена', seniority=0, awards=2)
for i in range(20):
    elena.check_if_it_is_time_for_upgrade()

Елена 1
Елена 1
Елена 1
Елена 2
Елена 2
Елена 2
Елена 2
Елена 2
Елена 2
Елена 2
Елена 3
Елена 3
Елена 3
Елена 3
Елена 3
Елена 3
Елена 3
Елена 4
Елена 4
Елена 4


# Регулярные выражения и основы синтаксического разбора

### Задание 1
Напишите функцию, которая принимает на вход строку и проверяет является ли она валидным транспортным номером (1 буква, 3 цифры, 2 буквы, 2-3 цифры). Обратите внимание, что не все буквы кириллического алфавита используются в транспортных номерах.

Если номер валиден, то функция должна возвращать отдельно номер и регион.

### Решение

In [87]:
import re

car_id = 'М259РВ178'

def car_num_valid(car_id):
    car_pattern = r'[АВЕКМНОРСТУХ]{1}[0-9]{3}[АВЕКМНОРСТУХ]{2}[0-9]{2,3}'
    if re.findall(car_pattern, car_id):
        if len(car_id) == 8:
            print(f'Результат: Номер валиден {car_id[0:6]}. Регион: {car_id[-2:]}')
        elif len(car_id) == 9:
            print(f'Результат: Номер валиден {car_id[0:6]}. Регион: {car_id[-3:]}')
    else:
        print('Результат: Номер не валиден')
        
car_num_valid(car_id)

Результат: Номер валиден М259РВ. Регион: 178


In [88]:
car_id = 'АБ22ВВ193'

def car_num_valid(car_id):
    car_pattern = r'[АВЕКМНОРСТУХ]{2}\d{3}[АВЕКМНОРСТУХ]{1}\d{2,3}'
    if re.findall(car_pattern, car_id):
        if len(car_id) == 8:
            print(f'Результат: Номер валиден {car_id[0:6]}. Регион: {car_id[-2:]}')
        elif len(car_id) == 9:
            print(f'Результат: Номер валиден {car_id[0:6]}. Регион: {car_id[-3:]}')
    else:
        print('Результат: Номер не валиден')
        
car_num_valid(car_id)

Результат: Номер не валиден


### Задание 2

Напишите функцию, которая будет удалять все последовательные повторы слов из заданной строки при помощи регулярных выражений.

### Решение

In [89]:
some_string = 'Напишите функцию функцию, которая будет будет будет будет удалять все все все все последовательные повторы слов из из из из заданной строки строки при помощи регулярных выражений'

In [90]:
re.findall(r'\w+', some_string)

['Напишите',
 'функцию',
 'функцию',
 'которая',
 'будет',
 'будет',
 'будет',
 'будет',
 'удалять',
 'все',
 'все',
 'все',
 'все',
 'последовательные',
 'повторы',
 'слов',
 'из',
 'из',
 'из',
 'из',
 'заданной',
 'строки',
 'строки',
 'при',
 'помощи',
 'регулярных',
 'выражений']

In [91]:
my_string = some_string

def delete_word(my_string):
    res = []
    for el in re.findall(r'\w+', some_string):
        if el not in res:
            res.append(el)
    print(' '.join(res), '.')
    
delete_word(my_string)

Напишите функцию которая будет удалять все последовательные повторы слов из заданной строки при помощи регулярных выражений .


In [92]:
re.sub(r'(\w+)(\s+\1)+', r'\1', some_string)

'Напишите функцию, которая будет удалять все последовательные повторы слов из заданной строки при помощи регулярных выражений'

In [93]:
re.sub(r'\b([^\W\d]+)(\s+\1)+\b', r'\1', some_string)

'Напишите функцию, которая будет удалять все последовательные повторы слов из заданной строки при помощи регулярных выражений'

### Задание 3
Напишите функцию, которая будет возвращать акроним по переданной в нее строке со словами.

### Решение

In [109]:
some_words = 'Информационные технологии'


def get_acronym(some_words):
    return re.sub(r'(\w)\w+(\s|$)', r'\1', some_words).upper()
    
print_acronym(some_words)

ИТ


In [110]:
some_words = 'Near Field Communication'

print_acronym(some_words)

NFC


### Задание 4

Напишите функцию, которая будет принимать на вход список email-адресов и выводить их распределение по доменным зонам.

### Решение

In [111]:
emails = ['test@gmail.com, xyz@test.in, test@ya.ru, xyz@mail.ru, xyz@ya.ru, xyz@gmail.com']

def domen(emails):
    result = r'(\w*\d*)@(\w*\.\w*)'
    domens = [re.search(result, email).group(2) for email in emails]
    for domen in set(domens):
        print(f'{domen}: {domens.count(domen)}')
            
count_domain(emails)

@gmail.com : 2
@test.in : 1
@ya.ru : 2
@mail.ru : 1


### Задание 5
Напишите функцию, которая будет подсчитывать сколько слов начинается на гласные, а сколько на согласные буквы в тексте (текст может быть написан как с использованием букв кириллицы, так и латиницы)

### Решение

In [97]:
some_text = """Эталонной реализацией Python является интерпретатор CPython, 
поддерживающий большинство активно используемых платформ. 
Он распространяется под свободной лицензией Python Software Foundation License, 
позволяющей использовать его без ограничений в любых приложениях, включая проприетарные."""

def count_word(some_text):
    list_vowels = re.findall(r'\b[ауоыиэяюёеАУОЫИЭЯЮЁЕ|aeiouAEIOU]\S+\b', some_text)
    list_consonants = re.findall(r'\b[бвгджзйклмнпрстфхцчшщБВГДЖЗЙКЛМНПРСТФХЦ|bcdfghjklmnpqrstvwxyzBCDFGHJKLMNPQRSTVWXYZ]\S+\b', some_text)
    print('Слов на гласные буквы:', len(list_vowels))
    print('Слов на согласные буквы:', len(list_consonants))
    
count_word(some_text)

Слов на гласные буквы: 9
Слов на согласные буквы: 20


In [98]:
some_text = """The American wife stood at the window looking out. 
Outside right under their window a cat was crouched under one of the dripping green tables. 
The cat was trying to make herself so compact that she would not be dripped on."""

count_word(some_text)

Слов на гласные буквы: 9
Слов на согласные буквы: 31


### Задание 6
Напишите функцию, которая будет проверять номер сотового телефона на валидность, если он валиден, то переводить его в формат:
+7-xxx-xxx-xx-xx
Постарайтесь предусмотреть как можно больше адекватных форматов изначального ввода номера.

### Решение

In [99]:
my_number_phone = '8(950)555-55-55'

my_pattern = re.findall(r'^\+?[78][-\(]?\s?[9]\d{2}\)?-?\s?\d{3}-?\s?\d{2}-?\s?\d{2}$', my_number_phone)

In [100]:
print(my_pattern)

['8(950)555-55-55']


In [101]:
def valid_number_phone(phone):
    pattern = r'^\+?[78][-\(]?\s?[9]\d{2}\)?-?\s?\d{3}-?\s?\d{2}-?\s?\d{2}$'
    if re.findall(pattern, phone):
        number_phone = re.findall(pattern, phone)
        res = []
        for el_1 in number_phone:
            for el_2 in el_1:
                try:
                    el_2 == int(el_2)
                    res.append(el_2)
                except ValueError:
                    pass
        my_str = ''.join(res)    
        print (f'Результат: +7-{my_str[1:4]}-{my_str[4:7]}-{my_str[7:9]}-{my_str[-2:]}')
    else:
        print('Номер не валиден')

In [102]:
valid_number_phone('423-555-55-5555')

Номер не валиден


In [103]:
valid_number_phone('8(950)555-55-55')

Результат: +7-950-555-55-55


In [104]:
valid_number_phone('+7 950 555-55-55')

Результат: +7-950-555-55-55


In [105]:
valid_number_phone('+7 955 555 55 55')

Результат: +7-955-555-55-55


In [106]:
valid_number_phone('7(950) 555-55-55')

Результат: +7-950-555-55-55


In [107]:
valid_number_phone('123-456-789')

Номер не валиден


In [108]:
valid_number_phone('7981-910-5464')

Результат: +7-981-910-54-64
